#pragma once

#define SCREEN_CAPTURE_INTERVAL_MILLISECONDS 16

#define IO_CONTEXT_IDLE_SLEEP_SECONDS 1

#define SOCKET_SCREEN_PORT 5343
#define SOCKET_CONTROL_PORT 4354

#define MULTICAST_ADDRESS "239.255.0.1"
#define MULTICAST_PORT 19533
#define MULTICAST_INTERVAL_SECONDS 1