//#define UDP_SOCKET_PORT 5445
//#define TCP_SOCKET_PORT 4435
#pragma once

#define SOCKET_SCREEN_PORT 5343
#define SOCKET_CONTROL_PORT 4354

enum OperationCode : uint16_t {
	NONE = 0,
	PROCESS_LIST,
	PROCESS_SUSPEND,
	PROCESS_RESUME,
	PROCESS_KILL,
	KEYBOARD_DOWN,
	MOUSE_MOVE,
	MOUSE_LEFT_DOWN,
	MOUSE_LEFT_UP,
	MOUSE_MIDDLE_DOWN,
	MOUSE_MIDDLE_UP,
	MOUSE_RIGHT_DOWN,
	MOUSE_RIGHT_UP,
	MOUSE_WHEEL_V,
	MOUSE_WHEEL_H,
	FS_LIST,
	FS_COPY,
	FS_MOVE,
	FS_WRITE,
	FS_DELETE
};